// Code generated by go-swagger; DO NOT EDIT.

package assettype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gsvc/api/am/models"
)

// GetAssetTypeOKCode is the HTTP code returned for type GetAssetTypeOK
const GetAssetTypeOKCode int = 200

/*
GetAssetTypeOK Returns the asset type

swagger:response getAssetTypeOK
*/
type GetAssetTypeOK struct {

	/*
	  In: Body
	*/
	Payload *models.AssetTypeResource `json:"body,omitempty"`
}

// NewGetAssetTypeOK creates GetAssetTypeOK with default headers values
func NewGetAssetTypeOK() *GetAssetTypeOK {

	return &GetAssetTypeOK{}
}

// WithPayload adds the payload to the get asset type o k response
func (o *GetAssetTypeOK) WithPayload(payload *models.AssetTypeResource) *GetAssetTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get asset type o k response
func (o *GetAssetTypeOK) SetPayload(payload *models.AssetTypeResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAssetTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAssetTypeNotModifiedCode is the HTTP code returned for type GetAssetTypeNotModified
const GetAssetTypeNotModifiedCode int = 304

/*
GetAssetTypeNotModified AssetType not changed

swagger:response getAssetTypeNotModified
*/
type GetAssetTypeNotModified struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetAssetTypeNotModified creates GetAssetTypeNotModified with default headers values
func NewGetAssetTypeNotModified() *GetAssetTypeNotModified {

	return &GetAssetTypeNotModified{}
}

// WithPayload adds the payload to the get asset type not modified response
func (o *GetAssetTypeNotModified) WithPayload(payload *models.Errors) *GetAssetTypeNotModified {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get asset type not modified response
func (o *GetAssetTypeNotModified) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAssetTypeNotModified) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(304)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAssetTypeBadRequestCode is the HTTP code returned for type GetAssetTypeBadRequest
const GetAssetTypeBadRequestCode int = 400

/*
GetAssetTypeBadRequest Invalid request

swagger:response getAssetTypeBadRequest
*/
type GetAssetTypeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetAssetTypeBadRequest creates GetAssetTypeBadRequest with default headers values
func NewGetAssetTypeBadRequest() *GetAssetTypeBadRequest {

	return &GetAssetTypeBadRequest{}
}

// WithPayload adds the payload to the get asset type bad request response
func (o *GetAssetTypeBadRequest) WithPayload(payload *models.Errors) *GetAssetTypeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get asset type bad request response
func (o *GetAssetTypeBadRequest) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAssetTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAssetTypeUnauthorizedCode is the HTTP code returned for type GetAssetTypeUnauthorized
const GetAssetTypeUnauthorizedCode int = 401

/*
GetAssetTypeUnauthorized User is not authenticated

swagger:response getAssetTypeUnauthorized
*/
type GetAssetTypeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetAssetTypeUnauthorized creates GetAssetTypeUnauthorized with default headers values
func NewGetAssetTypeUnauthorized() *GetAssetTypeUnauthorized {

	return &GetAssetTypeUnauthorized{}
}

// WithPayload adds the payload to the get asset type unauthorized response
func (o *GetAssetTypeUnauthorized) WithPayload(payload *models.Errors) *GetAssetTypeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get asset type unauthorized response
func (o *GetAssetTypeUnauthorized) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAssetTypeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAssetTypeForbiddenCode is the HTTP code returned for type GetAssetTypeForbidden
const GetAssetTypeForbiddenCode int = 403

/*
GetAssetTypeForbidden User is not authorized for request

swagger:response getAssetTypeForbidden
*/
type GetAssetTypeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetAssetTypeForbidden creates GetAssetTypeForbidden with default headers values
func NewGetAssetTypeForbidden() *GetAssetTypeForbidden {

	return &GetAssetTypeForbidden{}
}

// WithPayload adds the payload to the get asset type forbidden response
func (o *GetAssetTypeForbidden) WithPayload(payload *models.Errors) *GetAssetTypeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get asset type forbidden response
func (o *GetAssetTypeForbidden) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAssetTypeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAssetTypeInternalServerErrorCode is the HTTP code returned for type GetAssetTypeInternalServerError
const GetAssetTypeInternalServerErrorCode int = 500

/*
GetAssetTypeInternalServerError Server error, for more information see errorcode and message

swagger:response getAssetTypeInternalServerError
*/
type GetAssetTypeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewGetAssetTypeInternalServerError creates GetAssetTypeInternalServerError with default headers values
func NewGetAssetTypeInternalServerError() *GetAssetTypeInternalServerError {

	return &GetAssetTypeInternalServerError{}
}

// WithPayload adds the payload to the get asset type internal server error response
func (o *GetAssetTypeInternalServerError) WithPayload(payload *models.Errors) *GetAssetTypeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get asset type internal server error response
func (o *GetAssetTypeInternalServerError) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAssetTypeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
