// Code generated by go-swagger; DO NOT EDIT.

package assettype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// SaveAssetTypeHandlerFunc turns a function with the right signature into a save asset type handler
type SaveAssetTypeHandlerFunc func(SaveAssetTypeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SaveAssetTypeHandlerFunc) Handle(params SaveAssetTypeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SaveAssetTypeHandler interface for that can handle valid save asset type params
type SaveAssetTypeHandler interface {
	Handle(SaveAssetTypeParams, *models.Principal) middleware.Responder
}

// NewSaveAssetType creates a new http.Handler for the save asset type operation
func NewSaveAssetType(ctx *middleware.Context, handler SaveAssetTypeHandler) *SaveAssetType {
	return &SaveAssetType{Context: ctx, Handler: handler}
}

/*
	SaveAssetType swagger:route PUT /assettypes/{id} assettype saveAssetType

# Create or Update an asset type

Create or Update an asset type. Complete asset type model payload should be provided in request.

	<b> Following are the updates allowed</b>

* Asset type description can be updated.
* Asset type variable's can be created, updated and removed. Varaible length, default Value and Unit can be changed. The unit changes from the API does not compute any value changes derived after the unit changes, the values will remain as it is and only the unit will be updated. The length can only be increased of a string variable and it cannot be decreased.
* File assignments can be updated and removed.

* Aspects can be created, updated and removed, please refer sample payloads below

  - Create aspect
    {
    "name": "leftWing",
    "aspectTypeId": "mdsp.wing"
    }
  - Update aspect <b><u>aspectId should be provided in payload</u></b> (only name can be updated)
    {
    "name": "rightWing",
    "aspectId": "b9cbfc7073be4530887cdb1e71c932b8",
    "aspectTypeId": "mdsp.wing"
    }
  - To delete an aspect, aspect should not be part of aspects payload
*/
type SaveAssetType struct {
	Context *middleware.Context
	Handler SaveAssetTypeHandler
}

func (o *SaveAssetType) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSaveAssetTypeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
