// Code generated by go-swagger; DO NOT EDIT.

package assetmodellock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// PutAssetModelLockHandlerFunc turns a function with the right signature into a put asset model lock handler
type PutAssetModelLockHandlerFunc func(PutAssetModelLockParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutAssetModelLockHandlerFunc) Handle(params PutAssetModelLockParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutAssetModelLockHandler interface for that can handle valid put asset model lock params
type PutAssetModelLockHandler interface {
	Handle(PutAssetModelLockParams, *models.Principal) middleware.Responder
}

// NewPutAssetModelLock creates a new http.Handler for the put asset model lock operation
func NewPutAssetModelLock(ctx *middleware.Context, handler PutAssetModelLockHandler) *PutAssetModelLock {
	return &PutAssetModelLock{Context: ctx, Handler: handler}
}

/*
	PutAssetModelLock swagger:route PUT /model/lock assetmodellock putAssetModelLock

Enable/disable lock state of an asset model.

Enable/disable lock state of asset model at tenant level, managing restrictions on update/delete operations on assettypes and aspecttypes.
*/
type PutAssetModelLock struct {
	Context *middleware.Context
	Handler PutAssetModelLockHandler
}

func (o *PutAssetModelLock) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutAssetModelLockParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
