// Code generated by go-swagger; DO NOT EDIT.

package diagnostic_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gsvc/api/mc/models"
)

// GetDiagnosticInformationOKCode is the HTTP code returned for type GetDiagnosticInformationOK
const GetDiagnosticInformationOKCode int = 200

/*
GetDiagnosticInformationOK OK

swagger:response getDiagnosticInformationOK
*/
type GetDiagnosticInformationOK struct {

	/*
	  In: Body
	*/
	Payload *models.PagedDiagnosticInformation `json:"body,omitempty"`
}

// NewGetDiagnosticInformationOK creates GetDiagnosticInformationOK with default headers values
func NewGetDiagnosticInformationOK() *GetDiagnosticInformationOK {

	return &GetDiagnosticInformationOK{}
}

// WithPayload adds the payload to the get diagnostic information o k response
func (o *GetDiagnosticInformationOK) WithPayload(payload *models.PagedDiagnosticInformation) *GetDiagnosticInformationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get diagnostic information o k response
func (o *GetDiagnosticInformationOK) SetPayload(payload *models.PagedDiagnosticInformation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDiagnosticInformationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDiagnosticInformationBadRequestCode is the HTTP code returned for type GetDiagnosticInformationBadRequest
const GetDiagnosticInformationBadRequestCode int = 400

/*
GetDiagnosticInformationBadRequest Bad Request

swagger:response getDiagnosticInformationBadRequest
*/
type GetDiagnosticInformationBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Badrequest `json:"body,omitempty"`
}

// NewGetDiagnosticInformationBadRequest creates GetDiagnosticInformationBadRequest with default headers values
func NewGetDiagnosticInformationBadRequest() *GetDiagnosticInformationBadRequest {

	return &GetDiagnosticInformationBadRequest{}
}

// WithPayload adds the payload to the get diagnostic information bad request response
func (o *GetDiagnosticInformationBadRequest) WithPayload(payload *models.Badrequest) *GetDiagnosticInformationBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get diagnostic information bad request response
func (o *GetDiagnosticInformationBadRequest) SetPayload(payload *models.Badrequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDiagnosticInformationBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDiagnosticInformationUnauthorizedCode is the HTTP code returned for type GetDiagnosticInformationUnauthorized
const GetDiagnosticInformationUnauthorizedCode int = 401

/*
GetDiagnosticInformationUnauthorized Unauthorized

swagger:response getDiagnosticInformationUnauthorized
*/
type GetDiagnosticInformationUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetDiagnosticInformationUnauthorized creates GetDiagnosticInformationUnauthorized with default headers values
func NewGetDiagnosticInformationUnauthorized() *GetDiagnosticInformationUnauthorized {

	return &GetDiagnosticInformationUnauthorized{}
}

// WithPayload adds the payload to the get diagnostic information unauthorized response
func (o *GetDiagnosticInformationUnauthorized) WithPayload(payload *models.Unauthorized) *GetDiagnosticInformationUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get diagnostic information unauthorized response
func (o *GetDiagnosticInformationUnauthorized) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDiagnosticInformationUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDiagnosticInformationForbiddenCode is the HTTP code returned for type GetDiagnosticInformationForbidden
const GetDiagnosticInformationForbiddenCode int = 403

/*
GetDiagnosticInformationForbidden Forbidden

swagger:response getDiagnosticInformationForbidden
*/
type GetDiagnosticInformationForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Forbidden `json:"body,omitempty"`
}

// NewGetDiagnosticInformationForbidden creates GetDiagnosticInformationForbidden with default headers values
func NewGetDiagnosticInformationForbidden() *GetDiagnosticInformationForbidden {

	return &GetDiagnosticInformationForbidden{}
}

// WithPayload adds the payload to the get diagnostic information forbidden response
func (o *GetDiagnosticInformationForbidden) WithPayload(payload *models.Forbidden) *GetDiagnosticInformationForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get diagnostic information forbidden response
func (o *GetDiagnosticInformationForbidden) SetPayload(payload *models.Forbidden) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDiagnosticInformationForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetDiagnosticInformationDefault unexpected error

swagger:response getDiagnosticInformationDefault
*/
type GetDiagnosticInformationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDiagnosticInformationDefault creates GetDiagnosticInformationDefault with default headers values
func NewGetDiagnosticInformationDefault(code int) *GetDiagnosticInformationDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDiagnosticInformationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get diagnostic information default response
func (o *GetDiagnosticInformationDefault) WithStatusCode(code int) *GetDiagnosticInformationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get diagnostic information default response
func (o *GetDiagnosticInformationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get diagnostic information default response
func (o *GetDiagnosticInformationDefault) WithPayload(payload *models.Error) *GetDiagnosticInformationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get diagnostic information default response
func (o *GetDiagnosticInformationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDiagnosticInformationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
