kafka:
  brokers:
    - "172.18.0.41:9092"
  topic: "ts"
  groupId: "ts-cons-group"
  minBytes: 1
  maxBytes: 10e6
  # kafka.LastOffset = -1
  # kafka.FirstOffset = -2
  startOffSet: -1 
hbase:
  zookeeper: "172.18.0.131"
  table: "ts"

svc:
  stream:
    dir: "/data/asset"

http:
  address: "0.0.0.0:8000"


