// Code generated by go-swagger; DO NOT EDIT.

package agm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Agent agent
//
// swagger:model Agent
type Agent struct {

	// e tag
	// Example: 2
	ETag string `json:"eTag,omitempty"`

	// Unique identifier of the entity
	// Example: 3b27818ea09a46b48c7eb3fbd878349f
	// Required: true
	// Max Length: 36
	EntityID *string `json:"entityId"`

	// Unique identifier of the agent
	// Example: 3b27818ea09a46b48c7eb3fbd878349f
	// Max Length: 36
	ID string `json:"id,omitempty"`

	// Name must be unique per tenant.
	// Example: Nanobox Agent
	// Required: true
	// Max Length: 128
	Name *string `json:"name"`

	// security profile
	// Required: true
	// Enum: [SHARED_SECRET RSA_3072]
	SecurityProfile *string `json:"securityProfile"`
}

// Validate validates this agent
func (m *Agent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntityID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurityProfile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Agent) validateEntityID(formats strfmt.Registry) error {

	if err := validate.Required("entityId", "body", m.EntityID); err != nil {
		return err
	}

	if err := validate.MaxLength("entityId", "body", *m.EntityID, 36); err != nil {
		return err
	}

	return nil
}

func (m *Agent) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.MaxLength("id", "body", m.ID, 36); err != nil {
		return err
	}

	return nil
}

func (m *Agent) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 128); err != nil {
		return err
	}

	return nil
}

var agentTypeSecurityProfilePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SHARED_SECRET","RSA_3072"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		agentTypeSecurityProfilePropEnum = append(agentTypeSecurityProfilePropEnum, v)
	}
}

const (

	// AgentSecurityProfileSHAREDSECRET captures enum value "SHARED_SECRET"
	AgentSecurityProfileSHAREDSECRET string = "SHARED_SECRET"

	// AgentSecurityProfileRSA3072 captures enum value "RSA_3072"
	AgentSecurityProfileRSA3072 string = "RSA_3072"
)

// prop value enum
func (m *Agent) validateSecurityProfileEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, agentTypeSecurityProfilePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Agent) validateSecurityProfile(formats strfmt.Registry) error {

	if err := validate.Required("securityProfile", "body", m.SecurityProfile); err != nil {
		return err
	}

	// value enum
	if err := m.validateSecurityProfileEnum("securityProfile", "body", *m.SecurityProfile); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this agent based on context it is used
func (m *Agent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Agent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Agent) UnmarshalBinary(b []byte) error {
	var res Agent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
