// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetRootAssetParams creates a new GetRootAssetParams object
//
// There are no default values defined in the spec.
func NewGetRootAssetParams() GetRootAssetParams {

	return GetRootAssetParams{}
}

// GetRootAssetParams contains all the bound params for the get root asset operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRootAsset
type GetRootAssetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ETag hash of previous request to allow caching
	  In: header
	*/
	IfNoneMatch *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRootAssetParams() beforehand.
func (o *GetRootAssetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindIfNoneMatch(r.Header[http.CanonicalHeaderKey("If-None-Match")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIfNoneMatch binds and validates parameter IfNoneMatch from header.
func (o *GetRootAssetParams) bindIfNoneMatch(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.IfNoneMatch = &raw

	return nil
}
