// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// GetRootAssetHandlerFunc turns a function with the right signature into a get root asset handler
type GetRootAssetHandlerFunc func(GetRootAssetParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRootAssetHandlerFunc) Handle(params GetRootAssetParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetRootAssetHandler interface for that can handle valid get root asset params
type GetRootAssetHandler interface {
	Handle(GetRootAssetParams, *models.Principal) middleware.Responder
}

// NewGetRootAsset creates a new http.Handler for the get root asset operation
func NewGetRootAsset(ctx *middleware.Context, handler GetRootAssetHandler) *GetRootAsset {
	return &GetRootAsset{Context: ctx, Handler: handler}
}

/*
	GetRootAsset swagger:route GET /assets/root assets getRootAsset

Returns the root asset of the user.

Read the root asset of the user, from which the whole asset hierarchy can be rebuilt.
*/
type GetRootAsset struct {
	Context *middleware.Context
	Handler GetRootAssetHandler
}

func (o *GetRootAsset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRootAssetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
