// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewDeleteFileParams creates a new DeleteFileParams object
//
// There are no default values defined in the spec.
func NewDeleteFileParams() DeleteFileParams {

	return DeleteFileParams{}
}

// DeleteFileParams contains all the bound params for the delete file operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteFile
type DeleteFileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Last known version to facilitate optimistic locking
	  Required: true
	  In: header
	*/
	IfMatch string
	/*Unique identifier of the file.
	  Required: true
	  Pattern: [0-9A-F]{32}
	  In: path
	*/
	FileID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteFileParams() beforehand.
func (o *DeleteFileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindIfMatch(r.Header[http.CanonicalHeaderKey("If-Match")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rFileID, rhkFileID, _ := route.Params.GetOK("fileId")
	if err := o.bindFileID(rFileID, rhkFileID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIfMatch binds and validates parameter IfMatch from header.
func (o *DeleteFileParams) bindIfMatch(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("If-Match", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("If-Match", "header", raw); err != nil {
		return err
	}
	o.IfMatch = raw

	return nil
}

// bindFileID binds and validates parameter FileID from path.
func (o *DeleteFileParams) bindFileID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.FileID = raw

	if err := o.validateFileID(formats); err != nil {
		return err
	}

	return nil
}

// validateFileID carries on validations for parameter FileID
func (o *DeleteFileParams) validateFileID(formats strfmt.Registry) error {

	if err := validate.Pattern("fileId", "path", o.FileID, `[0-9A-F]{32}`); err != nil {
		return err
	}

	return nil
}
