// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// GetFileHandlerFunc turns a function with the right signature into a get file handler
type GetFileHandlerFunc func(GetFileParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFileHandlerFunc) Handle(params GetFileParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFileHandler interface for that can handle valid get file params
type GetFileHandler interface {
	Handle(GetFileParams, *models.Principal) middleware.Responder
}

// NewGetFile creates a new http.Handler for the get file operation
func NewGetFile(ctx *middleware.Context, handler GetFileHandler) *GetFile {
	return &GetFile{Context: ctx, Handler: handler}
}

/*
	GetFile swagger:route GET /files/{fileId} files getFile

# Returns a file's metadata by its id

Returns a file's metadata by its id
*/
type GetFile struct {
	Context *middleware.Context
	Handler GetFileHandler
}

func (o *GetFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFileParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
