// Code generated by go-swagger; DO NOT EDIT.

package structure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// ListAssetAspectsHandlerFunc turns a function with the right signature into a list asset aspects handler
type ListAssetAspectsHandlerFunc func(ListAssetAspectsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAssetAspectsHandlerFunc) Handle(params ListAssetAspectsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListAssetAspectsHandler interface for that can handle valid list asset aspects params
type ListAssetAspectsHandler interface {
	Handle(ListAssetAspectsParams, *models.Principal) middleware.Responder
}

// NewListAssetAspects creates a new http.Handler for the list asset aspects operation
func NewListAssetAspects(ctx *middleware.Context, handler ListAssetAspectsHandler) *ListAssetAspects {
	return &ListAssetAspects{Context: ctx, Handler: handler}
}

/*
	ListAssetAspects swagger:route GET /assets/{id}/aspects structure listAssetAspects

# Get all aspects of an asset

Get all static and dynamic aspects of a given asset
*/
type ListAssetAspects struct {
	Context *middleware.Context
	Handler ListAssetAspectsHandler
}

func (o *ListAssetAspects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListAssetAspectsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
