// Code generated by go-swagger; DO NOT EDIT.

package structure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gsvc/api/am/models"
)

// ListAssetVariablesOKCode is the HTTP code returned for type ListAssetVariablesOK
const ListAssetVariablesOKCode int = 200

/*
ListAssetVariablesOK Variables of the given asset matched by the given filter criterias

swagger:response listAssetVariablesOK
*/
type ListAssetVariablesOK struct {
	/*ETag hash of the resource

	 */
	ETag string `json:"ETag"`

	/*
	  In: Body
	*/
	Payload *models.VariableListResource `json:"body,omitempty"`
}

// NewListAssetVariablesOK creates ListAssetVariablesOK with default headers values
func NewListAssetVariablesOK() *ListAssetVariablesOK {

	return &ListAssetVariablesOK{}
}

// WithETag adds the eTag to the list asset variables o k response
func (o *ListAssetVariablesOK) WithETag(eTag string) *ListAssetVariablesOK {
	o.ETag = eTag
	return o
}

// SetETag sets the eTag to the list asset variables o k response
func (o *ListAssetVariablesOK) SetETag(eTag string) {
	o.ETag = eTag
}

// WithPayload adds the payload to the list asset variables o k response
func (o *ListAssetVariablesOK) WithPayload(payload *models.VariableListResource) *ListAssetVariablesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables o k response
func (o *ListAssetVariablesOK) SetPayload(payload *models.VariableListResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header ETag

	eTag := o.ETag
	if eTag != "" {
		rw.Header().Set("ETag", eTag)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAssetVariablesNotModifiedCode is the HTTP code returned for type ListAssetVariablesNotModified
const ListAssetVariablesNotModifiedCode int = 304

/*
ListAssetVariablesNotModified Resource variables have not been modified

swagger:response listAssetVariablesNotModified
*/
type ListAssetVariablesNotModified struct {
}

// NewListAssetVariablesNotModified creates ListAssetVariablesNotModified with default headers values
func NewListAssetVariablesNotModified() *ListAssetVariablesNotModified {

	return &ListAssetVariablesNotModified{}
}

// WriteResponse to the client
func (o *ListAssetVariablesNotModified) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(304)
}

// ListAssetVariablesBadRequestCode is the HTTP code returned for type ListAssetVariablesBadRequest
const ListAssetVariablesBadRequestCode int = 400

/*
ListAssetVariablesBadRequest Invalid request

swagger:response listAssetVariablesBadRequest
*/
type ListAssetVariablesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAssetVariablesBadRequest creates ListAssetVariablesBadRequest with default headers values
func NewListAssetVariablesBadRequest() *ListAssetVariablesBadRequest {

	return &ListAssetVariablesBadRequest{}
}

// WithPayload adds the payload to the list asset variables bad request response
func (o *ListAssetVariablesBadRequest) WithPayload(payload *models.Errors) *ListAssetVariablesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables bad request response
func (o *ListAssetVariablesBadRequest) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAssetVariablesUnauthorizedCode is the HTTP code returned for type ListAssetVariablesUnauthorized
const ListAssetVariablesUnauthorizedCode int = 401

/*
ListAssetVariablesUnauthorized User is not authenticated

swagger:response listAssetVariablesUnauthorized
*/
type ListAssetVariablesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAssetVariablesUnauthorized creates ListAssetVariablesUnauthorized with default headers values
func NewListAssetVariablesUnauthorized() *ListAssetVariablesUnauthorized {

	return &ListAssetVariablesUnauthorized{}
}

// WithPayload adds the payload to the list asset variables unauthorized response
func (o *ListAssetVariablesUnauthorized) WithPayload(payload *models.Errors) *ListAssetVariablesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables unauthorized response
func (o *ListAssetVariablesUnauthorized) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAssetVariablesForbiddenCode is the HTTP code returned for type ListAssetVariablesForbidden
const ListAssetVariablesForbiddenCode int = 403

/*
ListAssetVariablesForbidden User is not authorized for request

swagger:response listAssetVariablesForbidden
*/
type ListAssetVariablesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAssetVariablesForbidden creates ListAssetVariablesForbidden with default headers values
func NewListAssetVariablesForbidden() *ListAssetVariablesForbidden {

	return &ListAssetVariablesForbidden{}
}

// WithPayload adds the payload to the list asset variables forbidden response
func (o *ListAssetVariablesForbidden) WithPayload(payload *models.Errors) *ListAssetVariablesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables forbidden response
func (o *ListAssetVariablesForbidden) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAssetVariablesNotFoundCode is the HTTP code returned for type ListAssetVariablesNotFound
const ListAssetVariablesNotFoundCode int = 404

/*
ListAssetVariablesNotFound Asset not found

swagger:response listAssetVariablesNotFound
*/
type ListAssetVariablesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAssetVariablesNotFound creates ListAssetVariablesNotFound with default headers values
func NewListAssetVariablesNotFound() *ListAssetVariablesNotFound {

	return &ListAssetVariablesNotFound{}
}

// WithPayload adds the payload to the list asset variables not found response
func (o *ListAssetVariablesNotFound) WithPayload(payload *models.Errors) *ListAssetVariablesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables not found response
func (o *ListAssetVariablesNotFound) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAssetVariablesInternalServerErrorCode is the HTTP code returned for type ListAssetVariablesInternalServerError
const ListAssetVariablesInternalServerErrorCode int = 500

/*
ListAssetVariablesInternalServerError Server error, for more information see errorcode and message

swagger:response listAssetVariablesInternalServerError
*/
type ListAssetVariablesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAssetVariablesInternalServerError creates ListAssetVariablesInternalServerError with default headers values
func NewListAssetVariablesInternalServerError() *ListAssetVariablesInternalServerError {

	return &ListAssetVariablesInternalServerError{}
}

// WithPayload adds the payload to the list asset variables internal server error response
func (o *ListAssetVariablesInternalServerError) WithPayload(payload *models.Errors) *ListAssetVariablesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables internal server error response
func (o *ListAssetVariablesInternalServerError) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAssetVariablesServiceUnavailableCode is the HTTP code returned for type ListAssetVariablesServiceUnavailable
const ListAssetVariablesServiceUnavailableCode int = 503

/*
ListAssetVariablesServiceUnavailable Service unavailable, for more information see errorcode and message

swagger:response listAssetVariablesServiceUnavailable
*/
type ListAssetVariablesServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAssetVariablesServiceUnavailable creates ListAssetVariablesServiceUnavailable with default headers values
func NewListAssetVariablesServiceUnavailable() *ListAssetVariablesServiceUnavailable {

	return &ListAssetVariablesServiceUnavailable{}
}

// WithPayload adds the payload to the list asset variables service unavailable response
func (o *ListAssetVariablesServiceUnavailable) WithPayload(payload *models.Errors) *ListAssetVariablesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list asset variables service unavailable response
func (o *ListAssetVariablesServiceUnavailable) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAssetVariablesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
