// Code generated by go-swagger; DO NOT EDIT.

package data_source_configuration_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gsvc/api/agm/models"
)

// GetAgentsIDDataSourceConfigurationOKCode is the HTTP code returned for type GetAgentsIDDataSourceConfigurationOK
const GetAgentsIDDataSourceConfigurationOKCode int = 200

/*
GetAgentsIDDataSourceConfigurationOK OK

swagger:response getAgentsIdDataSourceConfigurationOK
*/
type GetAgentsIDDataSourceConfigurationOK struct {

	/*
	  In: Body
	*/
	Payload *models.DataSourceConfiguration `json:"body,omitempty"`
}

// NewGetAgentsIDDataSourceConfigurationOK creates GetAgentsIDDataSourceConfigurationOK with default headers values
func NewGetAgentsIDDataSourceConfigurationOK() *GetAgentsIDDataSourceConfigurationOK {

	return &GetAgentsIDDataSourceConfigurationOK{}
}

// WithPayload adds the payload to the get agents Id data source configuration o k response
func (o *GetAgentsIDDataSourceConfigurationOK) WithPayload(payload *models.DataSourceConfiguration) *GetAgentsIDDataSourceConfigurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agents Id data source configuration o k response
func (o *GetAgentsIDDataSourceConfigurationOK) SetPayload(payload *models.DataSourceConfiguration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentsIDDataSourceConfigurationBadRequestCode is the HTTP code returned for type GetAgentsIDDataSourceConfigurationBadRequest
const GetAgentsIDDataSourceConfigurationBadRequestCode int = 400

/*
GetAgentsIDDataSourceConfigurationBadRequest Bad Request

swagger:response getAgentsIdDataSourceConfigurationBadRequest
*/
type GetAgentsIDDataSourceConfigurationBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Badrequest `json:"body,omitempty"`
}

// NewGetAgentsIDDataSourceConfigurationBadRequest creates GetAgentsIDDataSourceConfigurationBadRequest with default headers values
func NewGetAgentsIDDataSourceConfigurationBadRequest() *GetAgentsIDDataSourceConfigurationBadRequest {

	return &GetAgentsIDDataSourceConfigurationBadRequest{}
}

// WithPayload adds the payload to the get agents Id data source configuration bad request response
func (o *GetAgentsIDDataSourceConfigurationBadRequest) WithPayload(payload *models.Badrequest) *GetAgentsIDDataSourceConfigurationBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agents Id data source configuration bad request response
func (o *GetAgentsIDDataSourceConfigurationBadRequest) SetPayload(payload *models.Badrequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentsIDDataSourceConfigurationUnauthorizedCode is the HTTP code returned for type GetAgentsIDDataSourceConfigurationUnauthorized
const GetAgentsIDDataSourceConfigurationUnauthorizedCode int = 401

/*
GetAgentsIDDataSourceConfigurationUnauthorized Unauthorized

swagger:response getAgentsIdDataSourceConfigurationUnauthorized
*/
type GetAgentsIDDataSourceConfigurationUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetAgentsIDDataSourceConfigurationUnauthorized creates GetAgentsIDDataSourceConfigurationUnauthorized with default headers values
func NewGetAgentsIDDataSourceConfigurationUnauthorized() *GetAgentsIDDataSourceConfigurationUnauthorized {

	return &GetAgentsIDDataSourceConfigurationUnauthorized{}
}

// WithPayload adds the payload to the get agents Id data source configuration unauthorized response
func (o *GetAgentsIDDataSourceConfigurationUnauthorized) WithPayload(payload *models.Unauthorized) *GetAgentsIDDataSourceConfigurationUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agents Id data source configuration unauthorized response
func (o *GetAgentsIDDataSourceConfigurationUnauthorized) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentsIDDataSourceConfigurationForbiddenCode is the HTTP code returned for type GetAgentsIDDataSourceConfigurationForbidden
const GetAgentsIDDataSourceConfigurationForbiddenCode int = 403

/*
GetAgentsIDDataSourceConfigurationForbidden Forbidden

swagger:response getAgentsIdDataSourceConfigurationForbidden
*/
type GetAgentsIDDataSourceConfigurationForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Forbidden `json:"body,omitempty"`
}

// NewGetAgentsIDDataSourceConfigurationForbidden creates GetAgentsIDDataSourceConfigurationForbidden with default headers values
func NewGetAgentsIDDataSourceConfigurationForbidden() *GetAgentsIDDataSourceConfigurationForbidden {

	return &GetAgentsIDDataSourceConfigurationForbidden{}
}

// WithPayload adds the payload to the get agents Id data source configuration forbidden response
func (o *GetAgentsIDDataSourceConfigurationForbidden) WithPayload(payload *models.Forbidden) *GetAgentsIDDataSourceConfigurationForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agents Id data source configuration forbidden response
func (o *GetAgentsIDDataSourceConfigurationForbidden) SetPayload(payload *models.Forbidden) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentsIDDataSourceConfigurationNotFoundCode is the HTTP code returned for type GetAgentsIDDataSourceConfigurationNotFound
const GetAgentsIDDataSourceConfigurationNotFoundCode int = 404

/*
GetAgentsIDDataSourceConfigurationNotFound Not Found

swagger:response getAgentsIdDataSourceConfigurationNotFound
*/
type GetAgentsIDDataSourceConfigurationNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Notfound `json:"body,omitempty"`
}

// NewGetAgentsIDDataSourceConfigurationNotFound creates GetAgentsIDDataSourceConfigurationNotFound with default headers values
func NewGetAgentsIDDataSourceConfigurationNotFound() *GetAgentsIDDataSourceConfigurationNotFound {

	return &GetAgentsIDDataSourceConfigurationNotFound{}
}

// WithPayload adds the payload to the get agents Id data source configuration not found response
func (o *GetAgentsIDDataSourceConfigurationNotFound) WithPayload(payload *models.Notfound) *GetAgentsIDDataSourceConfigurationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agents Id data source configuration not found response
func (o *GetAgentsIDDataSourceConfigurationNotFound) SetPayload(payload *models.Notfound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAgentsIDDataSourceConfigurationInternalServerErrorCode is the HTTP code returned for type GetAgentsIDDataSourceConfigurationInternalServerError
const GetAgentsIDDataSourceConfigurationInternalServerErrorCode int = 500

/*
GetAgentsIDDataSourceConfigurationInternalServerError unexpected error

swagger:response getAgentsIdDataSourceConfigurationInternalServerError
*/
type GetAgentsIDDataSourceConfigurationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAgentsIDDataSourceConfigurationInternalServerError creates GetAgentsIDDataSourceConfigurationInternalServerError with default headers values
func NewGetAgentsIDDataSourceConfigurationInternalServerError() *GetAgentsIDDataSourceConfigurationInternalServerError {

	return &GetAgentsIDDataSourceConfigurationInternalServerError{}
}

// WithPayload adds the payload to the get agents Id data source configuration internal server error response
func (o *GetAgentsIDDataSourceConfigurationInternalServerError) WithPayload(payload *models.Error) *GetAgentsIDDataSourceConfigurationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get agents Id data source configuration internal server error response
func (o *GetAgentsIDDataSourceConfigurationInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetAgentsIDDataSourceConfigurationDefault Other error with any status code and response body format.

swagger:response getAgentsIdDataSourceConfigurationDefault
*/
type GetAgentsIDDataSourceConfigurationDefault struct {
	_statusCode int
}

// NewGetAgentsIDDataSourceConfigurationDefault creates GetAgentsIDDataSourceConfigurationDefault with default headers values
func NewGetAgentsIDDataSourceConfigurationDefault(code int) *GetAgentsIDDataSourceConfigurationDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAgentsIDDataSourceConfigurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get agents ID data source configuration default response
func (o *GetAgentsIDDataSourceConfigurationDefault) WithStatusCode(code int) *GetAgentsIDDataSourceConfigurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get agents ID data source configuration default response
func (o *GetAgentsIDDataSourceConfigurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetAgentsIDDataSourceConfigurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
