// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BadrequestIAM badrequest i a m
//
// swagger:model BadrequestIAM
type BadrequestIAM struct {

	// error
	// Example: invalid_authorization_header
	Error string `json:"error,omitempty"`

	// An error message with Correlation-ID value.
	// Example: [feae1a0b-48fb-4af5-bc0d-7c96d8058e37] Header is missing.
	ErrorDescription string `json:"error_description,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this badrequest i a m
func (m *BadrequestIAM) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this badrequest i a m based on context it is used
func (m *BadrequestIAM) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BadrequestIAM) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BadrequestIAM) UnmarshalBinary(b []byte) error {
	var res BadrequestIAM
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
