// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Forbidden forbidden
//
// swagger:model Forbidden
type Forbidden struct {

	// id
	ID string `json:"id,omitempty"`

	// message
	// Example: Insufficient authorization for this resource.
	Message string `json:"message,omitempty"`
}

// Validate validates this forbidden
func (m *Forbidden) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this forbidden based on context it is used
func (m *Forbidden) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Forbidden) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Forbidden) UnmarshalBinary(b []byte) error {
	var res Forbidden
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
