{
 "title": "SR-Go-Dash",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "percentile_90_each_handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    sum(\n        rate(http_request_duration_seconds_bucket[10m])\n    ) by (handler, le)\n)"
    }
   ]
  },
  {
   "title": "percentile_99_whole_service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    rate(http_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "request_rate_by_handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n    rate(http_request_duration_seconds_count[30s])\n) by (handler)"
    }
   ]
  },
  {
   "title": "request_error_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"5..\"}[30s])"
    }
   ]
  }
 ]
}