// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gsvc/api/agm/models"
)

// DeleteAgentsIDNoContentCode is the HTTP code returned for type DeleteAgentsIDNoContent
const DeleteAgentsIDNoContentCode int = 204

/*
DeleteAgentsIDNoContent No Content

swagger:response deleteAgentsIdNoContent
*/
type DeleteAgentsIDNoContent struct {
}

// NewDeleteAgentsIDNoContent creates DeleteAgentsIDNoContent with default headers values
func NewDeleteAgentsIDNoContent() *DeleteAgentsIDNoContent {

	return &DeleteAgentsIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteAgentsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteAgentsIDBadRequestCode is the HTTP code returned for type DeleteAgentsIDBadRequest
const DeleteAgentsIDBadRequestCode int = 400

/*
DeleteAgentsIDBadRequest Bad Request

swagger:response deleteAgentsIdBadRequest
*/
type DeleteAgentsIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Badrequest `json:"body,omitempty"`
}

// NewDeleteAgentsIDBadRequest creates DeleteAgentsIDBadRequest with default headers values
func NewDeleteAgentsIDBadRequest() *DeleteAgentsIDBadRequest {

	return &DeleteAgentsIDBadRequest{}
}

// WithPayload adds the payload to the delete agents Id bad request response
func (o *DeleteAgentsIDBadRequest) WithPayload(payload *models.Badrequest) *DeleteAgentsIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete agents Id bad request response
func (o *DeleteAgentsIDBadRequest) SetPayload(payload *models.Badrequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAgentsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAgentsIDUnauthorizedCode is the HTTP code returned for type DeleteAgentsIDUnauthorized
const DeleteAgentsIDUnauthorizedCode int = 401

/*
DeleteAgentsIDUnauthorized Unauthorized

swagger:response deleteAgentsIdUnauthorized
*/
type DeleteAgentsIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewDeleteAgentsIDUnauthorized creates DeleteAgentsIDUnauthorized with default headers values
func NewDeleteAgentsIDUnauthorized() *DeleteAgentsIDUnauthorized {

	return &DeleteAgentsIDUnauthorized{}
}

// WithPayload adds the payload to the delete agents Id unauthorized response
func (o *DeleteAgentsIDUnauthorized) WithPayload(payload *models.Unauthorized) *DeleteAgentsIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete agents Id unauthorized response
func (o *DeleteAgentsIDUnauthorized) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAgentsIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAgentsIDForbiddenCode is the HTTP code returned for type DeleteAgentsIDForbidden
const DeleteAgentsIDForbiddenCode int = 403

/*
DeleteAgentsIDForbidden Forbidden

swagger:response deleteAgentsIdForbidden
*/
type DeleteAgentsIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Forbidden `json:"body,omitempty"`
}

// NewDeleteAgentsIDForbidden creates DeleteAgentsIDForbidden with default headers values
func NewDeleteAgentsIDForbidden() *DeleteAgentsIDForbidden {

	return &DeleteAgentsIDForbidden{}
}

// WithPayload adds the payload to the delete agents Id forbidden response
func (o *DeleteAgentsIDForbidden) WithPayload(payload *models.Forbidden) *DeleteAgentsIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete agents Id forbidden response
func (o *DeleteAgentsIDForbidden) SetPayload(payload *models.Forbidden) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAgentsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAgentsIDNotFoundCode is the HTTP code returned for type DeleteAgentsIDNotFound
const DeleteAgentsIDNotFoundCode int = 404

/*
DeleteAgentsIDNotFound Not Found

swagger:response deleteAgentsIdNotFound
*/
type DeleteAgentsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Notfound `json:"body,omitempty"`
}

// NewDeleteAgentsIDNotFound creates DeleteAgentsIDNotFound with default headers values
func NewDeleteAgentsIDNotFound() *DeleteAgentsIDNotFound {

	return &DeleteAgentsIDNotFound{}
}

// WithPayload adds the payload to the delete agents Id not found response
func (o *DeleteAgentsIDNotFound) WithPayload(payload *models.Notfound) *DeleteAgentsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete agents Id not found response
func (o *DeleteAgentsIDNotFound) SetPayload(payload *models.Notfound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAgentsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAgentsIDPreconditionFailedCode is the HTTP code returned for type DeleteAgentsIDPreconditionFailed
const DeleteAgentsIDPreconditionFailedCode int = 412

/*
DeleteAgentsIDPreconditionFailed Precondition Failed

swagger:response deleteAgentsIdPreconditionFailed
*/
type DeleteAgentsIDPreconditionFailed struct {

	/*
	  In: Body
	*/
	Payload *models.Preconditionfailed `json:"body,omitempty"`
}

// NewDeleteAgentsIDPreconditionFailed creates DeleteAgentsIDPreconditionFailed with default headers values
func NewDeleteAgentsIDPreconditionFailed() *DeleteAgentsIDPreconditionFailed {

	return &DeleteAgentsIDPreconditionFailed{}
}

// WithPayload adds the payload to the delete agents Id precondition failed response
func (o *DeleteAgentsIDPreconditionFailed) WithPayload(payload *models.Preconditionfailed) *DeleteAgentsIDPreconditionFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete agents Id precondition failed response
func (o *DeleteAgentsIDPreconditionFailed) SetPayload(payload *models.Preconditionfailed) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAgentsIDPreconditionFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(412)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAgentsIDInternalServerErrorCode is the HTTP code returned for type DeleteAgentsIDInternalServerError
const DeleteAgentsIDInternalServerErrorCode int = 500

/*
DeleteAgentsIDInternalServerError unexpected error

swagger:response deleteAgentsIdInternalServerError
*/
type DeleteAgentsIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAgentsIDInternalServerError creates DeleteAgentsIDInternalServerError with default headers values
func NewDeleteAgentsIDInternalServerError() *DeleteAgentsIDInternalServerError {

	return &DeleteAgentsIDInternalServerError{}
}

// WithPayload adds the payload to the delete agents Id internal server error response
func (o *DeleteAgentsIDInternalServerError) WithPayload(payload *models.Error) *DeleteAgentsIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete agents Id internal server error response
func (o *DeleteAgentsIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAgentsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DeleteAgentsIDDefault Other error with any status code and response body format.

swagger:response deleteAgentsIdDefault
*/
type DeleteAgentsIDDefault struct {
	_statusCode int
}

// NewDeleteAgentsIDDefault creates DeleteAgentsIDDefault with default headers values
func NewDeleteAgentsIDDefault(code int) *DeleteAgentsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteAgentsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete agents ID default response
func (o *DeleteAgentsIDDefault) WithStatusCode(code int) *DeleteAgentsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete agents ID default response
func (o *DeleteAgentsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *DeleteAgentsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
