// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/agm/models"
)

// DeleteAgentsIDHandlerFunc turns a function with the right signature into a delete agents ID handler
type DeleteAgentsIDHandlerFunc func(DeleteAgentsIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAgentsIDHandlerFunc) Handle(params DeleteAgentsIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteAgentsIDHandler interface for that can handle valid delete agents ID params
type DeleteAgentsIDHandler interface {
	Handle(DeleteAgentsIDParams, *models.Principal) middleware.Responder
}

// NewDeleteAgentsID creates a new http.Handler for the delete agents ID operation
func NewDeleteAgentsID(ctx *middleware.Context, handler DeleteAgentsIDHandler) *DeleteAgentsID {
	return &DeleteAgentsID{Context: ctx, Handler: handler}
}

/*
	DeleteAgentsID swagger:route DELETE /agents/{id} Agent Operations deleteAgentsId

# Delete agent

Deletes the agent for the given agent id.
*/
type DeleteAgentsID struct {
	Context *middleware.Context
	Handler DeleteAgentsIDHandler
}

func (o *DeleteAgentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAgentsIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
