// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/agm/models"
)

// GetAgentsIDStatusHandlerFunc turns a function with the right signature into a get agents ID status handler
type GetAgentsIDStatusHandlerFunc func(GetAgentsIDStatusParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAgentsIDStatusHandlerFunc) Handle(params GetAgentsIDStatusParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetAgentsIDStatusHandler interface for that can handle valid get agents ID status params
type GetAgentsIDStatusHandler interface {
	Handle(GetAgentsIDStatusParams, *models.Principal) middleware.Responder
}

// NewGetAgentsIDStatus creates a new http.Handler for the get agents ID status operation
func NewGetAgentsIDStatus(ctx *middleware.Context, handler GetAgentsIDStatusHandler) *GetAgentsIDStatus {
	return &GetAgentsIDStatus{Context: ctx, Handler: handler}
}

/*
	GetAgentsIDStatus swagger:route GET /agents/{id}/status Agent Operations getAgentsIdStatus

# Get online status

Gets online status.
*/
type GetAgentsIDStatus struct {
	Context *middleware.Context
	Handler GetAgentsIDStatusHandler
}

func (o *GetAgentsIDStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAgentsIDStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
