// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/agm/models"
)

// PutAgentsIDHandlerFunc turns a function with the right signature into a put agents ID handler
type PutAgentsIDHandlerFunc func(PutAgentsIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutAgentsIDHandlerFunc) Handle(params PutAgentsIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutAgentsIDHandler interface for that can handle valid put agents ID params
type PutAgentsIDHandler interface {
	Handle(PutAgentsIDParams, *models.Principal) middleware.Responder
}

// NewPutAgentsID creates a new http.Handler for the put agents ID operation
func NewPutAgentsID(ctx *middleware.Context, handler PutAgentsIDHandler) *PutAgentsID {
	return &PutAgentsID{Context: ctx, Handler: handler}
}

/*
	PutAgentsID swagger:route PUT /agents/{id} Agent Operations putAgentsId

# Update agent

Updates the agent for the given agent id with given parameters.
*/
type PutAgentsID struct {
	Context *middleware.Context
	Handler PutAgentsIDHandler
}

func (o *PutAgentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutAgentsIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
