kafka:
  brokers:
    - "172.18.0.41:9092"
  topic: "ts"
  groupId: "ts-cons-group"
  minBytes: 1
  maxBytes: 10e6
  # kafka.LastOffset = -1
  # kafka.FirstOffset = -2
  startOffSet: -1 
etcd:
  hosts:
    - "172.18.0.71:2379"
    
http:
  address: "0.0.0.0:8002"
basepath:
  timeseries: "/api/v1/timeseries/"
  stream: "/api/v1/stream/"

svc:
  stream:
    dir: "/data/asset"