// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// AspectID Aspect id is an internal id of an aspect associated with an asset type.
// Example: b9cbfc7073be4530887cdb1e71c932b8
//
// swagger:model AspectId
type AspectID string

// Validate validates this aspect Id
func (m AspectID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this aspect Id based on context it is used
func (m AspectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
