// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RootAssetResource root asset resource
//
// swagger:model RootAssetResource
type RootAssetResource struct {
	AssetResource

	// Hieararchy path is empty for the root asset
	// Example: []
	HierarchyPath []string `json:"hierarchyPath"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *RootAssetResource) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 AssetResource
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.AssetResource = aO0

	// AO1
	var dataAO1 struct {
		HierarchyPath []string `json:"hierarchyPath"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.HierarchyPath = dataAO1.HierarchyPath

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m RootAssetResource) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.AssetResource)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		HierarchyPath []string `json:"hierarchyPath"`
	}

	dataAO1.HierarchyPath = m.HierarchyPath

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this root asset resource
func (m *RootAssetResource) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with AssetResource
	if err := m.AssetResource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this root asset resource based on the context it is used
func (m *RootAssetResource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with AssetResource
	if err := m.AssetResource.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RootAssetResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RootAssetResource) UnmarshalBinary(b []byte) error {
	var res RootAssetResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
