// Code generated by go-swagger; DO NOT EDIT.

package registration_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"gsvc/api/agm/models"
)

// NewPutRegisterClientIDParams creates a new PutRegisterClientIDParams object
//
// There are no default values defined in the spec.
func NewPutRegisterClientIDParams() PutRegisterClientIDParams {

	return PutRegisterClientIDParams{}
}

// PutRegisterClientIDParams contains all the bound params for the put register client ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutRegisterClientID
type PutRegisterClientIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Registration Access Token value with Bearer authentication scheme. e.g :Bearer eyJh...
	  Required: true
	  In: header
	*/
	Authorization string
	/*Client identifier to update information.
	  Required: true
	  In: path
	*/
	ClientID string
	/*The client's key in JWKS for security profile RSA. If security profile is SHARED_SECRET there is only client_id in the JSON.
	  Required: true
	  In: body
	*/
	Keys *models.RotationKeys
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutRegisterClientIDParams() beforehand.
func (o *PutRegisterClientIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindAuthorization(r.Header[http.CanonicalHeaderKey("Authorization")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rClientID, rhkClientID, _ := route.Params.GetOK("client_id")
	if err := o.bindClientID(rClientID, rhkClientID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RotationKeys
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("keys", "body", ""))
			} else {
				res = append(res, errors.NewParseError("keys", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Keys = &body
			}
		}
	} else {
		res = append(res, errors.Required("keys", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthorization binds and validates parameter Authorization from header.
func (o *PutRegisterClientIDParams) bindAuthorization(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Authorization", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Authorization", "header", raw); err != nil {
		return err
	}
	o.Authorization = raw

	return nil
}

// bindClientID binds and validates parameter ClientID from path.
func (o *PutRegisterClientIDParams) bindClientID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ClientID = raw

	return nil
}
