// Code generated by go-swagger; DO NOT EDIT.

package aspecttype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// DeleteAspectTypeHandlerFunc turns a function with the right signature into a delete aspect type handler
type DeleteAspectTypeHandlerFunc func(DeleteAspectTypeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAspectTypeHandlerFunc) Handle(params DeleteAspectTypeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteAspectTypeHandler interface for that can handle valid delete aspect type params
type DeleteAspectTypeHandler interface {
	Handle(DeleteAspectTypeParams, *models.Principal) middleware.Responder
}

// NewDeleteAspectType creates a new http.Handler for the delete aspect type operation
func NewDeleteAspectType(ctx *middleware.Context, handler DeleteAspectTypeHandler) *DeleteAspectType {
	return &DeleteAspectType{Context: ctx, Handler: handler}
}

/*
	DeleteAspectType swagger:route DELETE /aspecttypes/{id} aspecttype deleteAspectType

# Delete aspect type

Delete an aspect type. Aspect type can only be deleted if there is no asset type using it.
*/
type DeleteAspectType struct {
	Context *middleware.Context
	Handler DeleteAspectTypeHandler
}

func (o *DeleteAspectType) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAspectTypeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
