// Code generated by go-swagger; DO NOT EDIT.

package aspecttype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/am/models"
)

// ListAspectTypesHandlerFunc turns a function with the right signature into a list aspect types handler
type ListAspectTypesHandlerFunc func(ListAspectTypesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAspectTypesHandlerFunc) Handle(params ListAspectTypesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListAspectTypesHandler interface for that can handle valid list aspect types params
type ListAspectTypesHandler interface {
	Handle(ListAspectTypesParams, *models.Principal) middleware.Responder
}

// NewListAspectTypes creates a new http.Handler for the list aspect types operation
func NewListAspectTypes(ctx *middleware.Context, handler ListAspectTypesHandler) *ListAspectTypes {
	return &ListAspectTypes{Context: ctx, Handler: handler}
}

/*
	ListAspectTypes swagger:route GET /aspecttypes aspecttype listAspectTypes

# List all aspect types

List all aspect types
*/
type ListAspectTypes struct {
	Context *middleware.Context
	Handler ListAspectTypesHandler
}

func (o *ListAspectTypes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListAspectTypesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
