// Code generated by go-swagger; DO NOT EDIT.

package mappings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gsvc/api/mc/models"
)

// GetDataPointMappingsOKCode is the HTTP code returned for type GetDataPointMappingsOK
const GetDataPointMappingsOKCode int = 200

/*
GetDataPointMappingsOK OK

swagger:response getDataPointMappingsOK
*/
type GetDataPointMappingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PagedMapping `json:"body,omitempty"`
}

// NewGetDataPointMappingsOK creates GetDataPointMappingsOK with default headers values
func NewGetDataPointMappingsOK() *GetDataPointMappingsOK {

	return &GetDataPointMappingsOK{}
}

// WithPayload adds the payload to the get data point mappings o k response
func (o *GetDataPointMappingsOK) WithPayload(payload *models.PagedMapping) *GetDataPointMappingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point mappings o k response
func (o *GetDataPointMappingsOK) SetPayload(payload *models.PagedMapping) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointMappingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataPointMappingsBadRequestCode is the HTTP code returned for type GetDataPointMappingsBadRequest
const GetDataPointMappingsBadRequestCode int = 400

/*
GetDataPointMappingsBadRequest Bad Request

swagger:response getDataPointMappingsBadRequest
*/
type GetDataPointMappingsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Badrequest `json:"body,omitempty"`
}

// NewGetDataPointMappingsBadRequest creates GetDataPointMappingsBadRequest with default headers values
func NewGetDataPointMappingsBadRequest() *GetDataPointMappingsBadRequest {

	return &GetDataPointMappingsBadRequest{}
}

// WithPayload adds the payload to the get data point mappings bad request response
func (o *GetDataPointMappingsBadRequest) WithPayload(payload *models.Badrequest) *GetDataPointMappingsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point mappings bad request response
func (o *GetDataPointMappingsBadRequest) SetPayload(payload *models.Badrequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointMappingsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataPointMappingsUnauthorizedCode is the HTTP code returned for type GetDataPointMappingsUnauthorized
const GetDataPointMappingsUnauthorizedCode int = 401

/*
GetDataPointMappingsUnauthorized Unauthorized

swagger:response getDataPointMappingsUnauthorized
*/
type GetDataPointMappingsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Unauthorized `json:"body,omitempty"`
}

// NewGetDataPointMappingsUnauthorized creates GetDataPointMappingsUnauthorized with default headers values
func NewGetDataPointMappingsUnauthorized() *GetDataPointMappingsUnauthorized {

	return &GetDataPointMappingsUnauthorized{}
}

// WithPayload adds the payload to the get data point mappings unauthorized response
func (o *GetDataPointMappingsUnauthorized) WithPayload(payload *models.Unauthorized) *GetDataPointMappingsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point mappings unauthorized response
func (o *GetDataPointMappingsUnauthorized) SetPayload(payload *models.Unauthorized) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointMappingsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataPointMappingsForbiddenCode is the HTTP code returned for type GetDataPointMappingsForbidden
const GetDataPointMappingsForbiddenCode int = 403

/*
GetDataPointMappingsForbidden Forbidden

swagger:response getDataPointMappingsForbidden
*/
type GetDataPointMappingsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Forbidden `json:"body,omitempty"`
}

// NewGetDataPointMappingsForbidden creates GetDataPointMappingsForbidden with default headers values
func NewGetDataPointMappingsForbidden() *GetDataPointMappingsForbidden {

	return &GetDataPointMappingsForbidden{}
}

// WithPayload adds the payload to the get data point mappings forbidden response
func (o *GetDataPointMappingsForbidden) WithPayload(payload *models.Forbidden) *GetDataPointMappingsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point mappings forbidden response
func (o *GetDataPointMappingsForbidden) SetPayload(payload *models.Forbidden) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointMappingsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetDataPointMappingsDefault unexpected error

swagger:response getDataPointMappingsDefault
*/
type GetDataPointMappingsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDataPointMappingsDefault creates GetDataPointMappingsDefault with default headers values
func NewGetDataPointMappingsDefault(code int) *GetDataPointMappingsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDataPointMappingsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get data point mappings default response
func (o *GetDataPointMappingsDefault) WithStatusCode(code int) *GetDataPointMappingsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get data point mappings default response
func (o *GetDataPointMappingsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get data point mappings default response
func (o *GetDataPointMappingsDefault) WithPayload(payload *models.Error) *GetDataPointMappingsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point mappings default response
func (o *GetDataPointMappingsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointMappingsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
