// Code generated by go-swagger; DO NOT EDIT.

package mappings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gsvc/api/mc/models"
)

// GetDataPointMappingsHandlerFunc turns a function with the right signature into a get data point mappings handler
type GetDataPointMappingsHandlerFunc func(GetDataPointMappingsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDataPointMappingsHandlerFunc) Handle(params GetDataPointMappingsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetDataPointMappingsHandler interface for that can handle valid get data point mappings params
type GetDataPointMappingsHandler interface {
	Handle(GetDataPointMappingsParams, *models.Principal) middleware.Responder
}

// NewGetDataPointMappings creates a new http.Handler for the get data point mappings operation
func NewGetDataPointMappings(ctx *middleware.Context, handler GetDataPointMappingsHandler) *GetDataPointMappings {
	return &GetDataPointMappings{Context: ctx, Handler: handler}
}

/*
	GetDataPointMappings swagger:route GET /dataPointMappings Mappings getDataPointMappings

Get mappings.

Retrieves a list of mappings.
*/
type GetDataPointMappings struct {
	Context *middleware.Context
	Handler GetDataPointMappingsHandler
}

func (o *GetDataPointMappings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDataPointMappingsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
