// Code generated by go-swagger; DO NOT EDIT.

package exchange

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostExchangeParams creates a new PostExchangeParams object
//
// There are no default values defined in the spec.
func NewPostExchangeParams() PostExchangeParams {

	return PostExchangeParams{}
}

// PostExchangeParams contains all the bound params for the post exchange operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostExchange
type PostExchangeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Multipart message.
	  Required: true
	  In: body
	*/
	Message io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostExchangeParams() beforehand.
func (o *PostExchangeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		o.Message = r.Body
	} else {
		res = append(res, errors.Required("message", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
